### ISSUE TITLE
cursive_table_view = 0.9.0 -> Is pancurses-backend depreciated?

### ISSUE THREAD

**Issue by stedingan** [BonsaiDen/cursive_table_view#12]
Hello, 

i updated a small programm using cursive and cursive_table_view to [Cargo.toml]
```

[dependencies.cursive]
version = "0.12"
default-features = false
features = ["pancurses-backend"]

[dependencies.cursive_table_view]
version = "0.9.0"
default-features = false
features = ["pancurses-backend"]
```

If i do a cargo build/run i get: 

> 
> 
> 11:56 AM	Cargo project update failed:
> 					Execution failed (exit code 101).
> 					        /usr/bin/cargo metadata --verbose --format-version 1 --all-features
> 					        stdout :     Updating crates.io index
> 					error: failed to select a version for `cursive_table_view`.
> 					    ... required by package `msprofit v1.0.2 (/home/andi/code/rust/msprofit)`
> 					versions that meet the requirements `^0.9.0` are: 0.9.0
> 					
> the package "msprofit" depends on "cursive_table_view", with features:
> "pancurses-backend" but "cursive_table_view" does not have these features.

Sadly i need windows as a platform so pancurses was my only option. Is the pancurses-backend depreciated? 

If i forgot any information or you need anything else please let me know.

Thanks for any information about this.
Have a nice day.
Best regards

**Comment by gyscos** [comment]
Hi!

Since version 0.9.0, you shouldn't need to specify the backend for `cursive_table_view` anymore; specifying it for `cursive` should be enough.

Though this lib still hasn't been updated for cursive 0.12, so for now it's only compatible with cursive 0.11. I will update it as soon as I get the chance.
