### ISSUE TITLE
Dynamic columns

### ISSUE THREAD

**Issue by linclelinkpart5** [BonsaiDen/cursive_table_view#18]
Hello, I'm planning on using `cursive_tables_view` to create a TUI music metadata editor, but I'm not sure if I can have a dynamically-created list of columns? I'd like to be able to have user decide which columns they'd like to see, similar to how Puddletag would do it. Is it possible?

**Comment by smallB007** [comment]
Hi there, yes that would be a great feature to have. 
@linclelinkpart5 Optionally you can read the configuration from "some place" and user will have to restart <- but this is last resort

**Comment by gyscos** [comment]
You probably can re-create the table view itself without having to restart the full application.

Though adding `add_column(&mut self, ...)` in addition to the current `column(self, ...)` may avoid having to re-create the view just for that.

**Comment by smallB007** [comment]
@gyscos I believe that those are simply essentials.

**Comment by gyscos** [comment]
latest master should include `{add,insert,remove}_column`.
