### ISSUE TITLE
Ownership?

### ISSUE THREAD

**Issue by matthiasbeyer** [BonsaiDen/cursive_table_view#2]
As with the cursive_tree_view crate, it seems like you're not interested in maintaining this any longer.

Would you transfer ownership of this crate to my account and give me access to the crates.io hosting? That would be awesome, I'm really interested in using this crate and continuing its development.

**Comment by gyscos** [comment]
@BonsaiDen gave me write access to these repos, I'll do my best and keep them up-to-date. PRs are always welcome!

**Comment by matthiasbeyer** [comment]
Even better.
