### ISSUE TITLE
Drawing column from top to bottom

### ISSUE THREAD

**Issue by smallB007** [BonsaiDen/cursive_table_view#22]
Hi, is there a way to actually draw column from top to bottom not just only for as long as there are items. What I mean by that is that if the table_view is of a size that for example fits 20 items but we only populated it with 3 the column will be drawn next to those 3 items only and the rest of the space is left empty. Perhaps pic will explain that better.
![Screenshot at 2020-07-20 07-35-39](https://user-images.githubusercontent.com/3456691/87903269-ddc91900-ca5b-11ea-989a-6f7c270582c8.png)
Thank you

**Comment by gyscos** [comment]
Hi, and thanks for the report!

This would indeed be doable here.

**Comment by gyscos** [comment]
On latest master it should work properly.

**Comment by smallB007** [comment]
Thank you very much for your work and the reply.
Unfortunately I wasn't able to check it because after updating to the latest I'm getting:
 the trait `cursive::view::ViewWrapper` is not implemented for `cursive_table_view::TableView<Foo, BasicColumn>`

I would be really grateful if somebody can help me with that issue.
