### ISSUE TITLE
Publish update to crates.io?

### ISSUE THREAD

**Issue by JoshMcguigan** [BonsaiDen/cursive_table_view#24]
Hello, thanks for all the great work on this crate as well as the core cursive crates. 

I was attempting to integrate this crate into a cursive project based on cursive `0.15`, but I was seeing compiler errors until I switched from the crates.io release of this crate (`0.12`) to pointing directly at github. I suspect this is because the version of this crate in crates.io has not been updated in a while? 

In the short term my work is not blocked because I can work against the github/master branch version of this crate, but it would be really great if an updated version could be published to crates.io.

Thanks again for all your work!

**Comment by palako** [comment]
Please do this. I spent easily 10 hours between yesterday and today troubleshooting this. I solved it this same way, only after searching in github for other projects that were using this library to see how they were doing it. Sadly I came here only to mention it, I should have come 10 hours ago and I would have found the solution.
I've seen other projects making a local copy of the code; this is clearly confusing folks, and unfortunately the error codes are not the most helpful trying to figure out what the exact issue is. One doesn't know about the details of cursive vs cursive_core when using the library to insert a table.

**Comment by gyscos** [comment]
Should be published now.
