### ISSUE TITLE
Example basics.rs doesn't build with cursive from git, branch main

### ISSUE THREAD

**Issue by smallB007** [BonsaiDen/cursive_table_view#32]
As the title says.

The error:

error[E0277]: the trait bound `cursive_core::views::Dialog: cursive::view::ViewWrapper` is not satisfied
   --> src/main.rs:123:19
    |
123 |     siv.add_layer(Dialog::around(table.with_name("table").min_size((50, 20))).title("Table View"));
    |         --------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `cursive::view::ViewWrapper` is not implemented for `cursive_core::views::Dialog`
    |         |
    |         required by a bound introduced by this call

**Comment by smallB007** [comment]
Hi, I managed to fix that by correcting some use etc.
Anyway, could you please tell me, how to deal with errors like this?

the trait bound cursive_core::views::Dialog: cursive::view::ViewWrapper is not satisfied

What I as a user of this lib can do to fix such issue?

Thank you

**Comment by gyscos** [comment]
Hi,
This error usually means that you are using two different versions of Cursive. This is most likely because this library still requires a previous version of Cursive, while your main application is using a more recent version.

The fix is to update this library to use the latest version of Cursive.

**Comment by smallB007** [comment]
This is the link to the example that I cannot compile:

https://ufile.io/f/jjskg
I believe that I'm using newest (from branch main) cursive as well as newest cursive_table_view.
Does not compile. If you could see for yourself it would be perhaps easier to explain. 
Thank you

**Comment by smallB007** [comment]
Hi
I decided to ping that issue.
I genuinely believe that there is a problem with compiling cursive_table_view with cursive from branch main (not 0.16.3 but branch main).
Could you please confirm that everything is fine on your end?

Thank you

Thank you.

**Comment by gyscos** [comment]
Hi,

Indeed it seems I didn't fully upstream some changes I made (and released to crates.io), should be fixed now. I also prepared it for the next release. It should now work with the latest cursive git branch.

**Comment by a6s5df6a54sd** [comment]
Hi,
Thank you for the reply and for fixing the issue.

**Comment by smallB007** [comment]
Hi,
Thank you for the reply and for fixing this issue.
