### ISSUE TITLE
set_selected_row does not scroll row into view

### ISSUE THREAD

**Issue by viveksjain** [BonsaiDen/cursive_table_view#35]
There seems to be an off-by-one somewhere that causes set_selected_row to not scroll the row into view (although it does select the correct row). To repro patch this line:
```
diff --git a/examples/basic.rs b/examples/basic.rs
index 0c2c802..36a1832 100644
--- a/examples/basic.rs
+++ b/examples/basic.rs
@@ -88,6 +88,7 @@ fn main() {
     }

     table.set_items(items);
+    table.set_selected_row(0);

     table.set_on_sort(|siv: &mut Cursive, column: BasicColumn, order: Ordering| {
         siv.add_layer(
```
Then run `cargo run --example basic`. Observed view:
![Screen Shot 2022-03-31 at 4 24 10 PM](https://user-images.githubusercontent.com/1541998/161165458-092a9d26-c1b6-4f18-a81c-c46607edf0cf.png)

Expected view:
![Screen Shot 2022-03-31 at 4 25 15 PM](https://user-images.githubusercontent.com/1541998/161165515-a6dace32-a64d-4719-8005-31947e47a173.png)

**Comment by gyscos** [comment]
Hi, and thanks for the report!

`set_selected_row` _should_ properly scroll to keep the element into view, but it seems to be buggy somehow. You can try setting the row to 20: it will scroll, but will miss the target by 1 row.

Will investigate to see if it's an issue here or in cursive's scroll module.

**Comment by viveksjain** [comment]
Thanks! (And thanks for all the work you've done on cursive!) Would appreciate you updating this issue once cursive is released with the fix.

**Comment by gyscos** [comment]
cursive-core 0.3.2 has been released, so you should be able to `cargo update` and it will be picked up.

In addition, cursive 0.18.0 has also been released to include a crossterm bump from back in March that I forgot to release.

**Comment by viveksjain** [comment]
Great, I can confirm the update fixes this issue in my app!
