### ISSUE TITLE
Update for 0.9

### ISSUE THREAD

**Issue by yorickdowne** [BonsaiDen/cursive_table_view#6]
0.9 split the sub_printer() method up into components. How would you draws columns now? Can you update this code to work with 0.9?

**Comment by yorickdowne** [comment]
I think I have this working. There's an issue in cursive 0.9 I'm still tracking down with BoxView::with_full_screen(). Once I'm convinced it doesn't impact this, I'll give you a PR.

**Comment by gyscos** [comment]
Fix is now in master (1784fefd8089f436e1411de728b2eb53d27bd49b).
